### ISSUE TITLE
tdestroy() is used which is gnu extension

### ISSUE THREAD

**Issue by AMDmi3** [jjgreen/cptutils#19]
```tdestroy()``` is called from ```tree_destroy()``` in ```src/common/identtab.c```. This is a gnu extension (as the comment in the file states) and there's no such function on e.g. FreeBSD. To build the project I've just commented it out, but that introduces a memory leak. Perhaps it could be replaced with recursive ```tdelete()``` or something?

**Comment by jjgreen** [comment]
Good idea, I've added a conditional on `__GNUC__` in  7086a53  so you should be able to compile without gcc till that's done.

**Comment by jjgreen** [comment]
I don't _think_ it's possible to use the exposed standard tree functions to destroy a tree, hence the existence of the nonstandard `tdestroy`.  Moreover, the structure of the tree nodes is opaque according to the standard, so it would not be possible to just copy gnulib's `tdestroy` into the code, at least not without the rest of `tsearch.c`, which seems excessive.  So I can live with the small memory leak on non-gcc compiles, at least one can now compile.  I've added a note to this effect in the code.

Please reopen this if issues persist.
